# Generated by Django 4.2.6 on 2023-10-23 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentHour',
            field=models.TimeField(default=datetime.time(2, 46, 5, 171104)),
        ),
    ]
