# Generated by Django 4.2.6 on 2023-10-23 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_appointmenthour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentHour',
            field=models.TimeField(default=datetime.datetime(2023, 10, 23, 2, 47, 2, 680167, tzinfo=datetime.timezone.utc)),
        ),
    ]
