# Generated by Django 4.2.6 on 2023-10-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_appointmenthour'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultingroom',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='consultingroom',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
