# Generated by Django 4.2.6 on 2023-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_consultingroom_email_consultingroom_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultingroom',
            name='qr_code',
            field=models.ImageField(null=True, upload_to='consultingroom-qrcodes/'),
        ),
    ]
