# Generated by Django 4.2.6 on 2024-01-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_consultingroom_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='id_patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.patient'),
        ),
    ]
