# Generated by Django 4.2.6 on 2024-01-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_confirmed_appointment_id_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Second_last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
