# Generated by Django 4.2.6 on 2024-01-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_patient_second_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PhoneNumber',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
