# Generated by Django 4.2.6 on 2024-02-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_patient_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Eage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Second_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
