# Generated by Django 4.2.6 on 2024-02-01 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_patient_eage_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_consultingRoom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.consultingroom'),
        ),
    ]
