# Generated by Django 4.2.6 on 2024-02-09 22:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_patient_id_consultingroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('createregisbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.createregisbase')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('id_consultingRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.consultingroom')),
            ],
            bases=('appointment.createregisbase',),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Programada', max_length=100),
        ),
        migrations.AlterField(
            model_name='createregisbase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('createregisbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.createregisbase')),
                ('date', models.DateField(db_comment='Fecha en la que el tratamiento normal fue entregado/realizado')),
                ('note', models.CharField(max_length=100)),
                ('dental_aucense', models.CharField(max_length=100)),
                ('conserved_teeth', models.CharField(max_length=100)),
                ('absence_teeth', models.CharField(max_length=100)),
                ('teeth_to_replace', models.CharField(max_length=100)),
                ('prosthesis_type', models.CharField(max_length=100)),
                ('prosthesis_description', models.CharField(max_length=100)),
                ('observations', models.CharField(max_length=100)),
                ('updated_price', models.FloatField()),
                ('prosthesis_procedure', models.JSONField(db_comment='Configuracion en caso de que el tratamineto sea protesis')),
                ('id_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.patient')),
                ('id_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.service')),
            ],
            bases=('appointment.createregisbase',),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('createregisbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.createregisbase')),
                ('contribution', models.CharField(max_length=50)),
                ('id_consultingRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.consultingroom')),
                ('id_treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.treatment')),
            ],
            bases=('appointment.createregisbase',),
        ),
    ]
