# Generated by Django 4.2.6 on 2024-02-14 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_createregisbase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='id_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
