# Generated by Django 4.2.6 on 2024-02-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_appointment_id_service_service_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='confirmed',
        ),
    ]
