# Generated by Django 4.2.6 on 2024-02-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_remove_appointment_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='updated_price',
            field=models.FloatField(null=True),
        ),
    ]
