# Generated by Django 4.2.6 on 2024-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_alter_treatment_updated_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='absence_teeth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='conserved_teeth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(db_comment='Fecha en la que el tratamiento normal fue entregado/realizado', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='dental_aucense',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='observations',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prosthesis_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prosthesis_procedure',
            field=models.JSONField(db_comment='Configuracion en caso de que el tratamineto sea protesis', null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prosthesis_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='teeth_to_replace',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
